### ISSUE TITLE
请帮看下这个问题，

### ISSUE THREAD

**Issue by cmj100424** [THUDM/ChatGLM-6B#809] opened 2023-04-25 05:53 UTC
### Is your feature request related to a problem? Please describe.

/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/requests/__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  RequestsDependencyWarning)
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "cli_demo.py", line 7, in <module>
    model = AutoModel.from_pretrained("model", trust_remote_code=True).half().cuda()
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/transformers/models/auto/auto_factory.py", line 456, in from_pretrained
    pretrained_model_name_or_path, module_file + ".py", class_name, **hub_kwargs, **kwargs
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/transformers/dynamic_module_utils.py", line 374, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/transformers/dynamic_module_utils.py", line 147, in get_class_in_module
    module = importlib.import_module(module_path)
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ma-user/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 15, in <module>
    from torch.nn.utils import skip_init
ImportError: cannot import name 'skip_init' from 'torch.nn.utils' (/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/torch/nn/utils/__init__.py)

### Solutions

请问GLM依赖那些版本的软件

**Comment by lwh9346** [comment] 2023-04-25 11:27
你的环境是按照`requirements.txt`安装的吗？

**Comment by cmj100424** [comment] 2023-04-25 11:58
是的

**Comment by cmj100424** [comment] 2023-04-25 11:59
> 你的环境是按照`requirements.txt`安装的吗？

是的

**Comment by ChenWarlock** [comment] 2023-04-26 02:46
skip_init不是pytorch2.0.0的么，可以更新一下pytorch

**Comment by zhangch9** [comment] 2023-08-16 11:40
Duplicate of [#517](https://github.com/THUDM/ChatGLM-6B/issues/517)

**Closed by zhangch9** 2023-08-16 11:40 UTC
