### ISSUE TITLE
get response error when run code: response, history = model.chat(tokenizer, "hello", history=[]) 

### ISSUE THREAD

**Issue by hetingyou** [THUDM/ChatGLM-6B#56] opened 2023-03-15 08:47 UTC
error info:

RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`

**Comment by duzx16** [comment] 2023-03-15 16:29
Duplicate of #38 
Please make sure you install PyTorch with CUDA support correctly.

**Closed by duzx16** 2023-03-15 16:29 UTC
