### ISSUE TITLE
ImportError: This modeling file requires the following packages that were not found in your environment: icetk. Run `pip install icetk`

### ISSUE THREAD

**Issue by mqormq** [THUDM/ChatGLM-6B#30] opened 2023-03-15 02:21 UTC
在windows上面运行好像有这个bug。我在conda环境中装过这个包了，但是运行时候还是找不到。

**Comment by duzx16** [comment] 2023-03-15 02:38
你是在Windows上运行的吗？Windows上需要`protobuf>=3.19.5,<3.20.1`才能正常使用`icetk`。你可以检查一下你的`protobuf`版本吗

**Comment by duzx16** [comment] 2023-03-15 02:41
Duplicate of #29

**Closed by duzx16** 2023-03-15 02:41 UTC

**Comment by czd2019** [comment] 2023-03-15 06:14
遇到同样的问题,按照requirement.txt安装了虚拟环境,运行cli_demo.py
报错
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "cli_demo.py", line 5, in <module>
    tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
  File "/root/anaconda3/envs/chatGPT/lib/python3.7/site-packages/transformers/models/auto/tokenization_auto.py", line 643, in from_pretrained
    pretrained_model_name_or_path, module_file + ".py", class_name, **kwargs
  File "/root/anaconda3/envs/chatGPT/lib/python3.7/site-packages/transformers/dynamic_module_utils.py", line 372, in get_class_from_dynamic_module
    local_files_only=local_files_only,
  File "/root/anaconda3/envs/chatGPT/lib/python3.7/site-packages/transformers/dynamic_module_utils.py", line 237, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/root/anaconda3/envs/chatGPT/lib/python3.7/site-packages/transformers/dynamic_module_utils.py", line 135, in check_imports
    "This modeling file requires the following packages that were not found in your environment: "
ImportError: This modeling file requires the following packages that were not found in your environment: icetk. Run `pip install icetk`


这是我安装的包,python版本是3.7
Package                  Version
------------------------ ----------
certifi                  2022.6.15
charset-normalizer       3.1.0
cpm-kernels              1.0.11
filelock                 3.9.1
huggingface-hub          0.13.2
icetk                    0.0.4
idna                     3.4
importlib-metadata       6.0.0
numpy                    1.21.6
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
packaging                23.0
Pillow                   9.4.0
pip                      22.1.2
protobuf                 3.19.5
PyYAML                   6.0
regex                    2022.10.31
requests                 2.28.2
sentencepiece            0.1.97
setuptools               58.0.4
tokenizers               0.13.2
torch                    1.13.1
torchvision              0.14.1
tqdm                     4.65.0
transformers             4.26.1
typing_extensions        4.5.0
urllib3                  1.26.15
wheel                    0.37.1
zipp                     3.15.0
