### ISSUE TITLE
[BUG/Help] 怎样测评耗时

### ISSUE THREAD

**Issue by xuguozhi** [THUDM/ChatGLM-6B#434] opened 2023-04-07 03:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

关于各种语言生成模型，该如何测评推理速度呢？有没有相关的参考？

### Steps To Reproduce

bash time_inference.sh

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment] 2023-04-12 16:10
Duplicate of #24

**Closed by duzx16** 2023-04-12 16:10 UTC
