### ISSUE TITLE
[BUG/Help] <ptuning 训练报错 size mismatch for lm_head.weight: copying a param with shape torch.Size([150528, 4096]) from checkpoint, the shape in current model is torch.Size([130528, 4096]).>

### ISSUE THREAD

**Issue by BLAIR-wy** [THUDM/ChatGLM-6B#537] opened 2023-04-12 02:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

下载了最新的代码了，运行bash train.sh报错 求助：

    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for ChatGLMForConditionalGeneration:
        size mismatch for transformer.word_embeddings.weight: copying a param with shape torch.Size([150528, 4096]) from checkpoint, the shape in current model is torch.Size([130528, 4096]).
        size mismatch for lm_head.weight: copying a param with shape torch.Size([150528, 4096]) from checkpoint, the shape in current model is torch.Size([130528, 4096]).
        You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.

### Steps To Reproduce

train.sh 设置如下
PRE_SEQ_LEN=128
LR=2e-2

CUDA_VISIBLE_DEVICES=0 python3 main.py \
    --do_train \
    --train_file dataset/trainingData.json \
    --validation_file dataset/devData.json \
    --prompt_column content \
    --response_column summary \
    --overwrite_cache \
    --model_name_or_path model/chatGLM6b/model \
    --output_dir output/adgen-chatglm-6b-pt-$PRE_SEQ_LEN-$LR \
    --overwrite_output_dir \
    --max_source_length 64 \
    --max_target_length 64 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --predict_with_generate \
    --max_steps 30 \
    --logging_steps 10 \
    --save_steps 10 \
    --learning_rate $LR \
    --pre_seq_len $PRE_SEQ_LEN \
    --quantization_bit 4

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by BLAIR-wy** [comment] 2023-04-12 02:30
torch.__version__
'1.13.1+cu117'
transformers==4.27.1

**Comment by duzx16** [comment] 2023-04-12 02:46
Duplicate of #431

**Closed by duzx16** 2023-04-12 02:46 UTC
