### ISSUE TITLE
[Feature] <title>能不能在docker下运行？

### ISSUE THREAD

**Issue by luckytalk** [THUDM/ChatGLM-6B#656] opened 2023-04-17 06:03 UTC
### Is your feature request related to a problem? Please describe.

能不能在docker下运行项目，需要预装载哪些组件？

### Solutions

希望给出docker的运行环境

**Comment by duzx16** [comment] 2023-04-17 06:09
Duplicate of #646

**Closed by duzx16** 2023-04-17 06:09 UTC
