### ISSUE TITLE
[Feature] Would the training process be released in the feature? 

### ISSUE THREAD

**Issue by camphora** [THUDM/ChatGLM-6B#177] opened 2023-03-21 05:47 UTC
### Is your feature request related to a problem? Please describe.

您好，ChatGLM-6B的效果相当令人惊艳，但是本项目并没有提供训练的代码和相关细节，仅提供了部署的版本，未来会考虑训练方面代码的开源么？

### Solutions

训练相关的内容的放出和讨论？

**Comment by duzx16** [comment] 2023-03-21 07:18
Duplicate of #3

**Closed by duzx16** 2023-03-21 07:18 UTC
