### ISSUE TITLE
[BUG/Help] 错误 Library cudart is not initialized

### ISSUE THREAD

**Issue by calvinzhan** [THUDM/ChatGLM-6B#489] opened 2023-04-10 07:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

代码运行到cudart.cudaGetDevice()是报错：错误 Library cudart is not initialized。
模型：THUDM/chatglm-6b-int4

所用组件版本如下：
transformers             4.27.1
torch                    2.0.0
torch-tb-profiler        0.4.0
torchaudio               2.0.1
torchmetrics             0.11.4
torchvision              0.15.1
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99

### Steps To Reproduce

  model = AutoModel.from_pretrained(settings.glm_path, local_files_only=True, trust_remote_code=True)
  model = model.half()
  model = model.to("cuda:6")
  model = model.eval()
...
model.stream_chat(tokenizer, prompt, history_formatted, max_length=max_length, top_p=top_p,temperature=temperature)

### Environment

```markdown
- OS:centos7
- Python:3.9.16
- Transformers:4.27.1
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by duzx16** [comment] 2023-04-12 16:08
Duplicate of #115

**Closed by duzx16** 2023-04-12 16:08 UTC
