### ISSUE TITLE
[BUG/Help] <title>ModuleNotFoundError: No module named 'transformers_modules.'

### ISSUE THREAD

**Issue by Song367** [THUDM/ChatGLM-6B#475] opened 2023-04-09 05:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "D:\workplace\CHATGLM\ChatGLM-6B\tt.py", line 2, in <module>
    tokenizer = AutoTokenizer.from_pretrained("../bb-model", trust_remote_code=True)
  File "D:\python\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 663, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(
  File "D:\python\lib\site-packages\transformers\dynamic_module_utils.py", line 399, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "D:\python\lib\site-packages\transformers\dynamic_module_utils.py", line 177, in get_class_in_module
    module = importlib.import_module(module_path)
  File "D:\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.'

### Steps To Reproduce

运行了文件 

from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("../bb-model", trust_remote_code=True)
model = AutoModel.from_pretrained("../bb-model", trust_remote_code=True).float()
response, history = model.chat(tokenizer, "你好", history=[])
print(response)

### Environment

```markdown
- OS: win11
- Python: 3.9
- Transformers: 4.27.1 
- PyTorch: 2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by Song367** [comment] 2023-04-09 05:50
cuda support : False

**Comment by duzx16** [comment] 2023-04-09 08:15
Duplicate of #310

**Closed by duzx16** 2023-04-09 08:15 UTC
