### ISSUE TITLE
Help #M1 Pro 运行报错

### ISSUE THREAD

**Issue by TreasureJade** [THUDM/ChatGLM-6B#550] opened 2023-04-12 09:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "/Users/hoho/py/ChatGLM-6B/cli_demo.py", line 6, in <module>
    tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
  File "/Users/hoho/anaconda3/envs/pytorch/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 679, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/Users/hoho/anaconda3/envs/pytorch/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1804, in from_pretrained
    return cls._from_pretrained(
  File "/Users/hoho/anaconda3/envs/pytorch/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1958, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/Users/hoho/.cache/huggingface/modules/transformers_modules/chatglm-6b/tokenization_chatglm.py", line 205, in __init__
    self.sp_tokenizer = SPTokenizer(vocab_file, num_image_tokens=num_image_tokens)
  File "/Users/hoho/.cache/huggingface/modules/transformers_modules/chatglm-6b/tokenization_chatglm.py", line 61, in __init__
    self.text_tokenizer = TextTokenizer(vocab_file)
  File "/Users/hoho/.cache/huggingface/modules/transformers_modules/chatglm-6b/tokenization_chatglm.py", line 22, in __init__
    self.sp.Load(model_path)
  File "/Users/hoho/anaconda3/envs/pytorch/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/Users/hoho/anaconda3/envs/pytorch/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: /Users/runner/work/sentencepiece/sentencepiece/src/sentencepiece_processor.cc(1102) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 

### Steps To Reproduce

1. python3  cli_demo.py 和python3 web_demo.py都有出现上述报错

### Environment

```markdown
- OS:MAC OS 13.3.1 
- Python:3.10
- Transformers:4.27.4
- PyTorch:2.1.0.dev20230411
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :true
```

**Comment by sdhou** [comment] 2023-04-12 10:35
最开始我也遇到了同样的问题 之后按照readme 手动下载模型文件 操作就行了 记得按照操作步骤修改一些代码

**Comment by duzx16** [comment] 2023-04-12 10:47
Duplicate of #480

**Closed by duzx16** 2023-04-12 10:47 UTC

**Comment by aomiga** [comment] 2023-04-13 02:18
我也遇到了相同的问题，是你怎么解决的啊？

**Comment by zhangjianliu** [comment] 2023-04-14 09:57
me too！

**Comment by illl-future** [comment] 2023-04-14 17:22
本地加载模型，修改THUDM/chatglm-6b为本地模型的绝对路径
