### ISSUE TITLE
[BUG/Help] deepspeed finetune后部署无返回结果

### ISSUE THREAD

**Issue by natureLanguageQing** [THUDM/ChatGLM-6B#560] opened 2023-04-12 15:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`from transformers import AutoTokenizer, AutoModel

# tokenizer = AutoTokenizer.from_pretrained('ptuning/outputs/adgen-chatglm-6b-pt-8-dev/checkpoint-6000', trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b",cache_dir='./chatglm-6b' ,trust_remote_code=True)
# home/ChatGLM-6B/ptuning/outputs/adgen-chatglm-6b-lr-1e-4-dev-32/checkpoint-6000
# home/ChatGLM-6B/ptuning/output/adgen-chatglm-6b-ft-1e-4/checkpoint-2000
# home/ChatGLM-6B/ptuning/output/adgen-chatglm-6b-ft-1e-4/checkpoint-1000
model = AutoModel.from_pretrained("output/adgen-chatglm-6b-ft-1e-4/checkpoint-1000",trust_remote_code=True).half().cuda()
model = model.eval()
import json

medical_dev = json.load(open("AdvertiseGen/medical_dev.32.128.512.json","r"))
import csv
with open("./checkpoint-1000.csv",'a') as f:
    
    write=csv.writer(f)
    write.writerow(['content','summary','chatglm_result'])
    for medical_dev_one in medical_dev:
        chatglm_result ,_ = model.chat(tokenizer, medical_dev_one['content'], history=[])
        print(chatglm_result)
        medical_dev_one['chatglm_result'] = chatglm_result
        print(medical_dev_one)
        write.writerow(medical_dev_one.values())
`

### Steps To Reproduce

在训练完成后测试没有返回结果

### Environment

```markdown
- OS:linux
- Python:python3.8
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by superbigsea** [comment] 2023-04-13 01:01
你好 请教下 deepspeed finetune 训练后怎么该推理的参数

**Comment by duzx16** [comment] 2023-04-13 05:37
Duplicate of #578

**Closed by duzx16** 2023-04-13 05:37 UTC

**Comment by natureLanguageQing** [comment] 2023-04-13 06:26
```
from transformers import AutoTokenizer, AutoModel, AutoConfig
import os
import torch
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b",cache_dir='/output/ChatGLM-6B/chatglm-6b', trust_remote_code=True)
config = AutoConfig.from_pretrained("THUDM/chatglm-6b",cache_dir='/output/ChatGLM-6B/chatglm-6b', trust_remote_code=True, pre_seq_len=128)
model = AutoModel.from_pretrained("THUDM/chatglm-6b",cache_dir='/output/ChatGLM-6B/chatglm-6b',config=config, trust_remote_code=True)
prefix_state_dict = torch.load(os.path.join("output/adgen-chatglm-6b-ft-1e-4/checkpoint-1000", "pytorch_model.bin"))
new_prefix_state_dict = {}
for k, v in prefix_state_dict.items():
    new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v
model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
# model = model.quantize(4)
model = model.half().cuda()
model.transformer.prefix_encoder.float()
model = model.eval()
```
ds full finetune的模型加载过程报错。
```
Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at THUDM/chatglm-6b and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[4], line 11
      9 for k, v in prefix_state_dict.items():
     10     new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v
---> 11 model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
     12 # model = model.quantize(4)
     13 model = model.half().cuda()

File /usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py:1671, in Module.load_state_dict(self, state_dict, strict)
   1666         error_msgs.insert(
   1667             0, 'Missing key(s) in state_dict: {}. '.format(
   1668                 ', '.join('"{}"'.format(k) for k in missing_keys)))
   1670 if len(error_msgs) > 0:
-> 1671     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   1672                        self.__class__.__name__, "\n\t".join(error_msgs)))
   1673 return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for PrefixEncoder:
	Missing key(s) in state_dict: "embedding.weight". 
	Unexpected key(s) in state_dict: ".weight", "layernorm.weight", "layernorm.bias", "ttention_layernorm.weight", "ttention_layernorm.bias", "_layernorm.weight", "_layernorm.bias", "attention_layernorm.weight", "attention_layernorm.bias", ".bias". 
```
