### ISSUE TITLE
[BUG/Help] chatGLM是否可以商用

### ISSUE THREAD

**Issue by archerdong** [THUDM/ChatGLM-6B#1031] opened 2023-05-16 03:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

请教一下chatGLM6B以及130B可以商用不，以及如果可以的话，有没有粗略的成本估算，比如一年多少钱

### Expected Behavior

s

### Steps To Reproduce

s

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment] 2023-05-18 06:23
Duplicate of #783

**Closed by duzx16** 2023-05-18 06:23 UTC
