### ISSUE TITLE
[Feature] <Online search and summarize>

### ISSUE THREAD

**Issue by ed-ckh** [THUDM/ChatGLM-6B#597] opened 2023-04-13 14:47 UTC
### Is your feature request related to a problem? Please describe.

It's better to let it search online and summarize the content, say, from the top 10 search results. Alternatively, just let it do a summary from the hyper-links provided by users.

### Solutions

Summarize the content of online search results by bullet points or a few short paragraphs. Similarly, do it for the hyperlinks that I provided.

### Additional context

Summarize the content of online search results by bullet points or a few short paragraphs. Similarly, do it for the hyperlinkes that I provided.

**Comment by duzx16** [comment] 2023-04-14 02:08
Duplicate of #198

**Closed by duzx16** 2023-04-14 02:08 UTC
