### ISSUE TITLE
[BUG/Help] <title>train.sh报错：IndexError: Out of range: piece id is out of range.

### ISSUE THREAD

**Issue by Leawnn** [THUDM/ChatGLM-6B#452] opened 2023-04-07 11:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/ailab/.conda/envs/py39/lib/python3.9/site-packages/transformers/tokeni │
│ zation_utils_base.py:3476 in decode                                          │
│                                                                              │
│   3473 │   │   # Convert inputs to python lists                              │
│   3474 │   │   token_ids = to_py_obj(token_ids)                              │
│   3475 │   │                                                                 │
│ ❱ 3476 │   │   return self._decode(                                          │
│   3477 │   │   │   token_ids=token_ids,                                      │
│   3478 │   │   │   skip_special_tokens=skip_special_tokens,                  │
│   3479 │   │   │   clean_up_tokenization_spaces=clean_up_tokenization_spaces │
│                                                                              │
│ /home/ailab/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b │
│ /9324de70a93207c9a310cf99d5d6261791489691/tokenization_chatglm.py:262 in     │
│ _decode                                                                      │
│                                                                              │
│   259 │   │   │   return ""                                                  │
│   260 │   │   if self.pad_token_id in token_ids:  # remove pad               │
│   261 │   │   │   token_ids = list(filter((self.pad_token_id).__ne__, token_ │
│ ❱ 262 │   │   return self.sp_tokenizer.decode(token_ids)                     │
│   263 │                                                                      │
│   264 │   def _convert_token_to_id(self, token):                             │
│   265 │   │   """ Converts a token (str) in an id using the vocab. """       │
│                                                                              │
│ /home/ailab/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b │
│ /9324de70a93207c9a310cf99d5d6261791489691/tokenization_chatglm.py:117 in     │
│ decode                                                                       │
│                                                                              │
│   114 │   def decode(self, text_ids: List[int]) -> str:                      │
│   115 │   │   ids = [int(_id) - self.num_image_tokens for _id in text_ids]   │
│   116 │   │   ids = [_id for _id in ids if _id >= 0]                         │
│ ❱ 117 │   │   text = self._get_text_tokenizer().decode(ids)                  │
│   118 │   │   text = text.replace("<n>", "\n")                               │
│   119 │   │   text = text.replace(SPTokenizer.get_tab_token(), "\t")         │
│   120 │   │   for i in range(2, self.max_blank_length + 1):                  │
│                                                                              │
│ /home/ailab/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b │
│ /9324de70a93207c9a310cf99d5d6261791489691/tokenization_chatglm.py:29 in      │
│ decode                                                                       │
│                                                                              │
│    26 │   │   return self.sp.EncodeAsIds(text)                               │
│    27 │                                                                      │
│    28 │   def decode(self, ids: List[int]):                                  │
│ ❱  29 │   │   return self.sp.DecodeIds(ids)                                  │
│    30 │                                                                      │
│    31 │   def tokenize(self, text):                                          │
│    32 │   │   return self.sp.EncodeAsPieces(text)                            │
│                                                                              │
│ /home/ailab/.conda/envs/py39/lib/python3.9/site-packages/sentencepiece/__ini │
│ t__.py:837 in DecodeIds                                                      │
│                                                                              │
│    834 │                                                                     │
│    835 │                                                                     │
│    836 │   def DecodeIds(self, input, out_type=str, **kwargs):               │
│ ❱  837 │     return self.Decode(input=input, out_type=out_type, **kwargs)    │
│    838 │                                                                     │
│    839 │                                                                     │
│    840 │   def DecodePiecesAsSerializedProto(self, input, out_type='serializ │
│                                                                              │
│ /home/ailab/.conda/envs/py39/lib/python3.9/site-packages/sentencepiece/__ini │
│ t__.py:780 in Decode                                                         │
│                                                                              │
│    777 │   │                                                                 │
│    778 │   │   if type(input) is list:                                       │
│    779 │   │     if len(input) == 0 or type(input[0]) is int:                │
│ ❱  780 │   │   │   return self._DecodeIds(input)                             │
│    781 │   │     if type(input[0]) is str:                                   │
│    782 │   │   │   return self._DecodePieces(input)                          │
│    783                                                                       │
│                                                                              │
│ /home/ailab/.conda/envs/py39/lib/python3.9/site-packages/sentencepiece/__ini │
│ t__.py:337 in _DecodeIds                                                     │
│                                                                              │
│    334 │   │   return _sentencepiece.SentencePieceProcessor__EncodeAsImmutab │
│    335 │                                                                     │
│    336 │   def _DecodeIds(self, ids):                                        │
│ ❱  337 │   │   return _sentencepiece.SentencePieceProcessor__DecodeIds(self, │
│    338 │                                                                     │
│    339 │   def _DecodePieces(self, pieces):                                  │
│    340 │   │   return _sentencepiece.SentencePieceProcessor__DecodePieces(se │
╰──────────────────────────────────────────────────────────────────────────────╯

### Expected Behavior

昨天还能运行的，今天就报错了，代码没有更改过

### Steps To Reproduce

none

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

### Anything else?

none

**Comment by duzx16** [comment] 2023-04-07 13:06
Duplicate of #438

**Closed by duzx16** 2023-04-07 13:06 UTC
