### ISSUE TITLE
如何增加max_new_tokens? 

### ISSUE THREAD

**Issue by Dfaker-HK** [THUDM/ChatGLM-6B#83] opened 2023-03-15 17:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Input length of input_ids is 2183, but `max_length` is set to 2048. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
之後回答便非常簡短, 但是我找不到如何增加max_new_tokens

### Steps To Reproduce

run web_demo.py

### Environment

```markdown
- OS: Windows 11
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by JiweiZh** [comment] 2023-03-21 05:15
model.chat(tokenizer, query, history, max_length=xxxx)

**Comment by zhangch9** [comment] 2023-08-15 11:49
Duplicate of [#17](https://github.com/THUDM/ChatGLM-6B/issues/17)

**Closed by zhangch9** 2023-08-15 11:49 UTC
