### ISSUE TITLE
 Unknown platform: darwin

### ISSUE THREAD

**Issue by zhaopengme** [THUDM/ChatGLM-6B#21] opened 2023-03-14 12:41 UTC
mac m1 无法运行

**Comment by chaucerling** [comment] 2023-03-14 13:11
```
File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/cpm_kernels/__init__.py", line 1, in <module>
    from . import library
File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/cpm_kernels/library/__init__.py", line 1, in <module>
    from . import nvrtc
File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/cpm_kernels/library/nvrtc.py", line 5, in <module>
    nvrtc = Lib("nvrtc")
File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/cpm_kernels/library/base.py", line 59, in __init__
    raise RuntimeError("Unknown platform: %s" % sys.platform)
```
报错提示 cpm_kernels 不支持 arm

**Comment by duzx16** [comment] 2023-03-14 13:19
Duplicate of #6

**Closed by duzx16** 2023-03-14 13:19 UTC

**Comment by wenfan919** [comment] 2023-04-01 14:22
RuntimeError: Error(s) in loading state_dict for ChatGLMForConditionalGeneration:
	size mismatch for transformer.layers.0.attention.query_key_value.weight: copying a param with shape torch.Size([12288, 2048]) from checkpoint, the shape in current model is torch.Size([12288, 4096]).

the same error!!!
